services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment: {}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    hostname: mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mqtt:/mosquitto/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./youtube:/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  mpd:
    image: tobi312/rpi-mpd:alpine
    container_name: mpd
    restart: unless-stopped
    ports:
      - "6600:6600"
    volumes:
      - ./youtube:/var/lib/mpd/music:ro
      - ./mpd/config:/root/.config
      - ./mpd/data:/var/lib/mpd/data
      - ./mpd/mpd.conf:/etc/mpd.conf:rw
    # Devices may be needed to output audio to your local host hardware
    devices:
      - /dev/snd:/dev/snd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd:latest
    container_name: mympd
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 8080:8080/tcp
    environment:
      # Notice: After the first start all environment variables are ignored, except loglevel.
      MPD_HOST: mpd
      MPD_PORT: 6600
      MYMPD_SSL: false
      MYMPD_HTTP_HOST: 0.0.0.0
      MYMPD_ACL: +0.0.0.0/0
      #MYMPD_MYMPD_URI: http://ha.local:8080
    volumes:
      - ./youtube/:/var/lib/mpd/music:ro
      - ./mpd/playlists/:/var/lib/mpd/playlists/:ro
      - ./mympd/lib:/var/lib/mympd/:rw
      - ./mympd/cachedir:/var/cache/mympd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  ai:
    image: ai:latest
    build:
      context: .
      dockerfile: ./ai/Dockerfile
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: ai
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  whisper:
    image: whisper:latest
    build:
      context: .
      dockerfile: ./whisper.cpp/Dockerfile
    container_name: whisper
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
  voice:
    image: voice:latest
    build:
      context: .
      dockerfile: ./voice/Dockerfile
    container_name: voice
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
