services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${HOME}/config:/config
      - ${HOME}/media:/media
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ${HOME}/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment: {}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    hostname: mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HOME}/mqtt:/mosquitto/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${HOME}/media:/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  mass:
    image: ghcr.io/music-assistant/server:latest
    container_name: mass
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${$HOME}/mass/data:/data/
      - ${HOME}/media:/media:ro
    environment:
      - LOG_LEVEL=info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  mpd:
    image: tobi312/rpi-mpd:alpine
    container_name: mpd
    restart: unless-stopped
    ports:
      - "6600:6600"
    volumes:
      - ${HOME}/media:/var/lib/mpd/music:ro
      - ${HOME}/mpd/config:/root/.config
      - ${HOME}/mpd/data:/var/lib/mpd/data
      - ${HOME}/mpd/mpd.conf:/etc/mpd.conf:rw
    # Devices may be needed to output audio to your local host hardware
    devices:
      - /dev/snd:/dev/snd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  mympd:
    image: ghcr.io/jcorporation/mympd/mympd:latest
    container_name: mympd
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 8080:8080/tcp
    environment:
      # Notice: After the first start all environment variables are ignored, except loglevel.
      MPD_HOST: mpd
      MPD_PORT: 6600
      MYMPD_SSL: false
      MYMPD_HTTP_HOST: 0.0.0.0
      MYMPD_ACL: +0.0.0.0/0
      #MYMPD_MYMPD_URI: http://ha.local:8080
    volumes:
      - ${HOME}/media:/var/lib/mpd/music:ro
      - ${HOME}/mpd/playlists/:/var/lib/mpd/playlists/:ro
      - ${HOME}/mympd/lib:/var/lib/mympd/:rw
      - ${HOME}/mympd/cachedir:/var/cache/mympd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  whisper:
    image: whisper:latest
    build:
      context: .
      dockerfile: ./whisper/Dockerfile
    container_name: whisper
    restart: unless-stopped
    depends_on:
      wyoming-whisper-api-client:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  wyoming-whisper-api-client:
    image: ghcr.io/ser/wyoming-whisper-api-client:latest
    container_name: wyoming-whisper-api-client
    ports:
      - 10300:10300
    command:
      - --debug
      - --uri
      - tcp://0.0.0.0:10300
      - --api
      - http://whisper:8080/inference
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  kokoro:
    image: kokoro:latest
    build:
      context: .
      dockerfile: ./kokoro/Dockerfile
    container_name: kokoro
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080/tcp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  lva:
    container_name: linux-voice-assistant
    hostname: lva
    image: ghcr.io/ohf-voice/linux-voice-assistant:latest
    restart: unless-stopped
    network_mode: host
    user: "${LVA_USER_ID:-1000}:${LVA_USER_GROUP:-1000}"
    env_file:
      - .env
    group_add:
      - audio
    # Priority for audio process
    cap_add:
      - SYS_NICE
    volumes:
      - /run/user/$LVA_USER_ID:/run/user/$LVA_USER_ID
      - /run/user/$LVA_USER_ID/pulse/native:/run/user/$LVA_USER_ID/pulse/native
      - /etc/machine-id:/etc/machine-id:ro
      - wakeword_data:/app/local
      - configuration:/app/configuration
      - ${HOME}/media:/media
    depends_on:
      lva-init:
        condition: service_completed_successfully
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  lva-init:
    image: alpine
    container_name: lva-init
    env_file:
      - .env
    volumes:
      - wakeword_data:/app/local
      - configuration:/app/configuration
    command: chown -R ${LVA_USER_ID:-1000}:${LVA_USER_GROUP:-1000} /app/local /app/configuration

volumes:
  wakeword_data:
  configuration:
